# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install: pip install -r requirements.txt coveralls
script: python manage.py test --with-coverage --cover-package={{ cookiecutter.app_name }}
after_success: coveralls
